### ISSUE TITLE
Typo Separator in DateRangePicker View

### ISSUE THREAD

**Issue by wdog** [Nayjest/Grids#120]
Hi I've noticed the in the file `resources/views/default/components/filters/date_range_picker.php`
at row 28  #[https://github.com/Nayjest/Grids/blob/master/resources/views/default/components/filters/date_range_picker.php#L28]

```php
text = start.format(options.format) + ' — ' + end.format(options.format);
```
the separator is `—` and not `-`
Is it a typo or there's a reason for it?

**Comment by Nayjest** [comment]
There is en-dash if I'm not mistaken and that is correct character for dates range. See http://www.thepunctuationguide.com/en-dash.html

**Comment by Nayjest** [comment]
But looks like there is another issue, from previous link:

> There should be no space between the en dash and the adjacent material

(fixed in master branch now)

**Comment by wdog** [comment]
I wrote because in the `daterangepicker.js`  the separator is defined as

```javascript
this.separator = ' - ';
```

and the it is used to split the default values

```javascript
split = val.split(this.separator);
```

**Comment by Nayjest** [comment]
Does it create a problem? I just don't know what functionality it affects, because demo works fine: http://grids-demo.herokuapp.com/demo/example4?example_grid4
I don't want to change separator to ' - ' because it's semantically incorrect.
Perhaps it's better to change daterangepicker.separator to '—' via JS in DateRangePicker View if it creates problems.

Any suggestions?

**Comment by rodrigoxj32** [comment]
Hello, in my case this generates an error, since moment does not recognize '-'
if I change it manually to '-' this already works, I'm working on a laravel project and the only non-optimal solution I found was using -> setJsOptions () but I lose the range selection doing this.

![captura de pantalla 209](https://user-images.githubusercontent.com/14839387/43052255-2ce2f826-8de1-11e8-9299-a84fc3625067.png)

![captura de pantalla 210](https://user-images.githubusercontent.com/14839387/43052259-385f4ed4-8de1-11e8-9450-6315b2f74457.png)
