### ISSUE TITLE
concat field sort

### ISSUE THREAD

**Issue by getcrud** [Nayjest/Grids#146]
i used field with concat it can show but when sort by that column it have error
`SELECT *
FROM (
    SELECT [EntryDate]
        ,[ExitDate]
        ,[JobTitle]
        ,[user_id]
        ,Title_en + ' ' + FirstName_en + ' ' + MiddleName_en + ' ' + LastName_en AS name_en
        ,Title_th + ' ' + FirstName_th + ' ' + MiddleName_th + ' ' + LastName_th AS name_th
        ,row_number() OVER (
            ORDER BY [name_en] DESC
            ) AS row_num
    FROM [users_hr]
    ) AS temp_table
WHERE row_num BETWEEN 21
        AND 40`
 i need query by
 `SELECT *
FROM (
    SELECT [EntryDate]
        ,[ExitDate]
        ,[JobTitle]
        ,[user_id]
        ,Title_en + ' ' + FirstName_en + ' ' + MiddleName_en + ' ' + LastName_en AS name_en
        ,Title_th + ' ' + FirstName_th + ' ' + MiddleName_th + ' ' + LastName_th AS name_th
        ,row_number() OVER (
            ORDER BY Title_en + ' ' + FirstName_en + ' ' + MiddleName_en + ' ' + LastName_en DESC
            ) AS row_num
    FROM [users_hr]
    ) AS temp_table
WHERE row_num BETWEEN 21
        AND 40`

may i add custom order by when sort by this field?

**Comment by Nayjest** [comment]
Hi!
1. Try to list columns and add alias for concatenated column in outer select instead of "Select *", then you can name your grid column according to that alias and make it sortable (but you will need some hacks to perform filtering if you need  because aliases can't be used in SQL WHERE section, you will need to use $fiter->setFilteringFunc() initialized by callback that will add correct condition to query builder).
2. If just calling $queryBuilder->orderBy() will not help you create required query, you need to iplement your own component that cen do all query changes in prepare() method  (`$grid->getConfig()->getDataProvider()->getBuilder()` will give you access to query builder).
3. Finally you can process input in controller and do whatever you want with your query before creating grid. But anyway you need to render some controls. Use \Nayjest\Grids\Components\RenderFunc component initialized by callback that returns HTML to render whatever you want in any place of grid.

Please give me know if it helped.

**Comment by getcrud** [comment]
i change FilterConfig by add **orderBy**

                                    $provider->getBuilder()
                                        ->where(function ($query) use ($val) {
                                            $query->where('users_hr.Title_th', 'LIKE', "%$val%")
                                                ->orWhere('users_hr.FirstName_th', 'LIKE', "%$val%")
                                                ->orWhere('users_hr.MiddleName_th', 'LIKE', "%$val%")
                                                ->orWhere('users_hr.LastName_th', 'LIKE', "%$val%");
                                        })
                                        ->orderBy(DB::raw("Title_th + ' ' + FirstName_th + ' ' + MiddleName_th + ' ' + LastName_th"));


it work in first page but error in pagination because order by Title_en + ' ' + FirstName_en + ' ' + MiddleName_en + ' ' + LastName_en DESC, **name_en DESC**

**Comment by Nayjest** [comment]
Can you share error / exception message & trace ?

**Comment by Nayjest** [comment]
```
DB::raw("Title_th + ' ' + FirstName_th + ' ' + MiddleName_th + ' ' + LastName_th")
```
Strange code. Do you use MYSQL?
Maybe you need:
```
DB::raw("CONCAT(Title_th, ' ', FirstName_th, ' ', MiddleName_th, ' ', LastName_th")
```
?
