### ISSUE TITLE
Eager Loading is not working

### ISSUE THREAD

**Issue by cpttripzz** [Nayjest/Grids#41]
I am using an eager loaded query builder and yet I can see that my relations are still getting queried for each row...

$grid = new Grid(
			(new GridConfig)
				->setDataProvider(
					new EloquentDataProvider(Customer::with('Country'))
				)
				->setName('Customers')
				->setPageSize(50)
				->setColumns([

					(new FieldConfig)
						->setName('country.name')
						->setLabel('Country')
						->setSortable(true)
....

**Comment by Nayjest** [comment]
Hi! 
I need some research to say, why your relations are still getting queried for each row.

By the way, grid filters will not work for columns from related models by default, you will need to override filtering function (see setFilteringFunc method). And I'm not sure that sorting will work.

So, in any case, if you need filtering of sorting using columns from related models, I recommend to use joins:
Example:
```php
new EloquentDataProvider(
     Customer::leftJoin('countries', 'countries.id', '=' 'customers.country_id')
)
```

**Comment by cpttripzz** [comment]
Thanks for responding.

I tried this but the model is trying to load the dynamic attribute each time calling the model's __get function and the model's $this->relations is null so it does  $this->getRelationshipFromMethod($key) resulting in a new query each time. Seems like a problem with how laravel is loading the relations.

$query = Customer::leftJoin('country', 'customers.Country', '=','country.id' );
		$grid = new Grid(
			(new GridConfig)
				->setDataProvider(
					new EloquentDataProvider($query)

Btw I also tried your DBAL Data Provider but I kept getting Paginator class not found.

**Comment by Nayjest** [comment]
Provide full trace of error "Paginator class not found", please (if it's possible). 

Regarding loading the dynamic attributes:
Maybe you used join but forgot to replace column names?
For example, if you use $field->setName('country.name'), it will call $model->country that's relation and load it.  
But if you already joined 'country' table, you can get it's fields directly from Customer model.
If customer has no "name" field and "country" has it, use $field->setName('name') to get country name.
If there is naming conflict, specify aliases for selected columns:
``` php
$query = Customer
    ::leftJoin('country', 'customers.country_id', '=','country.id' )
    ->select('customer.*')
    ->addSelect('country.name as country_name')
)
```
If you use MySQL, grid filters for column_name in this case may not work, becouse MySQL don't allows to specify aliases in WHERE SQL section.
i. e. 
```sql
SELECT name as country_name FROM countries WHERE country_name = ''Israel"
```
Isn't valid query.
But
```sql
SELECT name as country_name FROM countries ORDER BY country_name
```
Will work fine, therefore sorting will fork.

To fix filtering for aliased columns, you need to override filtering function to use 'country.name' in SQL instead of 'country_name':
```php
$filterConfig->setFilteringFunc(function($val, EloquentDataProvider $provider) {
     $provider->getBuilder()->where('country.name', '=', $val);
});
```

**Comment by cpttripzz** [comment]
That worked, thanks so much for your help and your excellent plugin.

**Comment by Nayjest** [comment]
>> If you like I could update your documentation for eager loading, I think this is a pretty common issue
Great! I would appretiate it!

You can create page in https://github.com/Nayjest/Grids/wiki  or fork repo, upd. readme.md and make pull request.
