### ISSUE TITLE
Overwrite pager path

### ISSUE THREAD

**Issue by lsaintmaxent** [Nayjest/Grids#49]
Hey men, firstable awesome work here, thanks a lot.

Do you know if it's possible to overwrite the path of the grid pager in the grid declaration (in controllers) ?

I need to overwrite it and i changed in Pager :
        $paginator = $this->grid->getConfig()
            ->getDataProvider()
            ->getPaginator();
		$paginator->setPath("/extranet/public/client");
Is it possible to use something like : 
(new OneCellRow)
->setComponents([
	(new Pager)
           ->setPath('/extranet/public')
]).

Thanks a lot for what you've done and sorry if my question is in the wrong place.

Louis

**Comment by Nayjest** [comment]
Hi!
It's fine place for questions.

I don't see setPath method in Larave4 paginator, so looks like you use Laravel 5.
In this case you need to create your own pagination component extended from Nayjest\Grids\Components\Laravel5\Pager
Example:
```php 
namespace My\App;
use Nayjest\Grids\Components\Laravel5\Pager;
class Pager extends BasePager
{
    protected $path;
    public function setPath($path)
    {
        $this->path = $path;
        return $this;
    }
    public function getPath()
    {
        return $this->path;
    }
    protected function setupPaginationForLinks()
    {
        /** @var  Paginator $paginator */
        $paginator = $this->grid->getConfig()
            ->getDataProvider()
            ->getPaginator();
        if ($this->path !== null) {
            $paginator->setPath($this->path);
        }
        $paginator->setPageName("{$this->input_key}[page]");
    }
}
```

And use it in grid instead of standard pagination:

```php
...
$gridConfig->setComponents([
    new THead,
    (new TFoot)
        ->setComponents([
            (new OneCellRow)
                ->setComponents([
                    (new \My\App\Pager)
                        ->setPath($myPath)
                    ,
                ]) 
        ])
    ,
])
```
That's all!

Little offtop,
It's interesting for me, why you need to use custom URL path.

For example, if you have some page with grid that can be accessible using few urls and you need to use one url for one group of users and another url for other users, it's better to perform redirect before showing grid.

Or you have something like a widget with grid somewhere in sidebar and when paginating, it must change url to the page where this grid is rendered in the central content area?

* I'm just guessing where $paginator->setPath() can be needed in any Laravel app's

**Comment by lsaintmaxent** [comment]
Thanks for your quick answer, it's really helpfull.

Firstable, i'm new to Laravel 5 and i'm pretty sure there is a better way to do what i'm doing but it's a small project with few days of work so i can't spend much time looking for a better way to do it.

On my server, i have a website on the baseURL and an extranet on pattern baseURL/extranet.
My apache config is probably wrong but seems to work right now if i access with pattern BaseURL/extranet/public.

The problem with grids is that when the pagination links are setup they link to baseURL/grid_name?page2 (or something like that, don't remember exactly the url) but they don't keep the /extranet/public before the grid name.

So with my wonderfull apache config, the pagination links to my website error page (content not found) -_-.

I know i'm doing wrong in my apache config but it's pretty complicated to setup a Vhost and my company helpdesk don't want to help me.

Thanks for everything,
Have a nice day.

**Comment by Nayjest** [comment]
Thanks for interesting use case )

**Comment by amenk** [comment]
@lsaintmaxent Did you encounter the same problem for Sorting? Did you solve it? See also #176
