### ISSUE TITLE
Access to a filtered page of the grid

### ISSUE THREAD

**Issue by lsaintmaxent** [Nayjest/Grids#77]
Hello there,

I would love your help on a tricky point.

I want to store (in session ?) filters the user has used and redirect to his filtered grid after my function.

For example.
A grid with 4 columns: ID, NAME, ADRESS and a button "edit".
The user has set his filter (name begin with 'a' and adress contains '425')
When he clic on edit, a form used to edit the row is displayed (that button call a function in the controller).
After that function, I use redirect('people') to display all my people.

Now i would like to display only people that were resulting from the select filters name begin with an 'a' and adress containing '425'.

I'm trying to retrieve url parameters in my controller, and redirect to a page /people?people_list[filters][name-=]=a ...

Do you know if there is a better to do so ?

Appreciate so much you library, again, awesome job !

Louis.

**Comment by Nayjest** [comment]
Hi
It's fine to retrive url parameters in controller. If you want to organize business logic better you can create your own grid component for this purpose. 
See \Nayjest\Grids\Components\CsvExport and it's view template as example.
You may use link instead of button (syled as button) and use something like this:
```php
<a href="<?= $grid->getInputProcessor()->getUrl(['do_edit' => $current_row_id_if_you_need]) ?>">Edit</a>
```
Link will point to current URL with new 'do_edit' GET parameter.
Then in your component's initilize method:
```php
public function initialize(Grid $grid)
    {
        parent::initialize($grid);
        if ($id = $grid->getInputProcessor()->getValue('do_edit')) {
            // make redirect using HTTP headers and terminate application to avoid rendering current page, etc.
        };
    }
```

Also if you need, you may override grid row component  (See \Nayjest\Grids\GridConfig::setRowComponent) and there override grid cell components to add some logic there.

But if you want to get solution ASAP, it's ok to do that in controller.

**Comment by lsaintmaxent** [comment]
Thanks a lot man,

I think it will work really soon using your advices.

Take care :)
